import { useState } from "react";
import { hospitalApi } from "../../hospitalApi";

export default function AddPatient({ go }) {
  const [done,setDone] = useState(false); const [error,setError] = useState(""); const [saving,setSaving]=useState(false);
  const [form,setForm] = useState({firstName:"",lastName:"",email:"",phone:"",dateOfBirth:"",gender:"",insured:"",insuranceProvider:"",insuranceNumber:"",consent:false});
  const field = (key) => (event) => setForm({...form,[key]:event.target.type === "checkbox" ? event.target.checked : event.target.value});
  async function submit(event){event.preventDefault();if(!form.firstName||!form.lastName||!form.email||!form.phone||!form.dateOfBirth||!form.gender||!form.consent)return setError("Complete required fields and confirm patient consent");setSaving(true);setError("");try{const result=await hospitalApi.registerPatient({...form,consentConfirmed:form.consent});sessionStorage.setItem("selectedPatientId",result.patient.id);setDone(true)}catch(reason){setError(reason.message)}finally{setSaving(false)}}
  if(done)return <div className="screen-overlay"><div className="result-dialog"><span>✓</span><h2>Patient account successfully created</h2><p>You can now schedule an appointment for the patient and keep track of their record status.</p><aside>ⓘ A secure link will be sent to the patient’s registered email and phone number, to complete profile verification.</aside><button onClick={() => go("patient-profile")}>Proceed</button></div></div>;
  return <div className="screen-overlay"><form className="patient-form" onSubmit={submit}><header><button type="button" onClick={() => go("patients")}>←</button><h2>Add New Patient</h2></header><h3>Patient Information</h3><div>{[["First Name","firstName","text"],["Last Name","lastName","text"],["Email","email","email"],["Phone Number","phone","tel"],["Date of Birth","dateOfBirth","date"]].map(([label,key,type])=><label key={key}>{label}<input type={type} value={form[key]} onChange={field(key)} placeholder={`Enter ${label}`} /></label>)}<label>Gender<select value={form.gender} onChange={field("gender")}><option value="">Select Gender</option><option>Female</option><option>Male</option><option>Other</option></select></label><label>Does the Patient have Health Insurance?<select value={form.insured} onChange={field("insured")}><option value="">Select Option</option><option>No</option><option>Yes</option></select></label><label>Insurance Provider<input value={form.insuranceProvider} onChange={field("insuranceProvider")} placeholder="Select Provider" /></label><label>Insurance Number<input value={form.insuranceNumber} onChange={field("insuranceNumber")} placeholder="Enter insurance ID" /></label></div><label className="consent"><input type="checkbox" checked={form.consent} onChange={field("consent")} />By creating this account, I confirm the patient has consented to store their medical records on AxonLink.</label>{error&&<p className="patient-form-error">{error}</p>}<button className="patient-submit" disabled={saving}>{saving?"Sending invitation…":"Create Account"}</button></form></div>;
}
