import { useEffect, useState } from "react";
import HospitalChrome from "../HospitalChrome";
import { formatDate, formatTime } from "../hospitalData";
import { hospitalApi } from "../../hospitalApi";

export default function AppointmentDetails({ go }) {
  const id=sessionStorage.getItem("selectedAppointmentId");
  const [appointment,setAppointment]=useState(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
  const [menu,setMenu]=useState(false);
  useEffect(()=>{let live=true;hospitalApi.listAppointments().then(result=>{const found=(result.appointments||[]).find(item=>item.id===id);if(live)setAppointment(found?{...found,start:found.date,type:found.visitType,status:found.status==="CONFIRMED"?"UPCOMING":found.status==="CANCELLED"?"CANCELED":found.status}:null)}).catch(reason=>{if(live)setError(reason.message)}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[id]);
  if(loading)return <HospitalChrome title="Appointment Details" active="appointments" go={go}><div className="appointment-empty details-empty"><p>Loading appointment…</p></div></HospitalChrome>;
  if(!appointment)return <HospitalChrome title="←  Appointment Details" active="appointments" go={go}><div className="appointment-empty details-empty"><h3>Appointment not found</h3><p>{error||"Select an appointment from the appointment page."}</p><button onClick={()=>go("appointments")}>Back to appointments</button></div></HospitalChrome>;
  const status=appointment.status||"UPCOMING"; const complete=status==="COMPLETED"; const ongoing=status==="ONGOING"; const canceled=status==="CANCELED";
  const setStatus=async(value)=>{const apiStatus=value==="CANCELED"?"CANCELLED":value;try{const result=await hospitalApi.updateAppointment(appointment.id,{status:apiStatus});setAppointment(current=>({...current,...result.appointment,start:result.appointment.date,type:result.appointment.visitType,status:value}));setMenu(false)}catch(reason){setError(reason.message)}};
  return <HospitalChrome title="←  Appointment Details" active="appointments" go={go}><main className="appointment-details"><aside><i>{appointment.patient?.[0]}</i><h2>{appointment.patient}</h2><em className={status.toLowerCase()}>{status}</em><section><p><span>Patient ID</span><b>#{appointment.patientId||appointment.id.slice(0,7)}</b></p><p><span>Type</span><b>{appointment.type||"Follow-Up"}</b></p><p><span>Duration</span><b>{appointment.duration||"00m : 00s"}</b></p><p><span>Date</span><b>{formatDate(appointment.start)}</b></p><p><span>Time</span><b>{formatTime(appointment.start)}</b></p></section><p>Assigned to <b>{appointment.clinician||"Available doctor"}</b></p><div className="action-wrap"><button onClick={()=>setMenu(!menu)}>Admin Action⌄</button>{menu&&<div className="appointment-menu action-menu"><button>Reassign Doctor</button><button>Reschedule</button><button onClick={()=>setStatus("COMPLETED")}>Mark as Completed</button><button className="danger" onClick={()=>setStatus("CANCELED")}>Cancel Appointment</button></div>}</div></aside><section className="consultation"><h2>Consultation Information</h2>{complete?<CompletedDetails item={appointment}/>:<div className="consultation-state"><span>▤</span><h2>{canceled?"Canceled":ongoing?"Ongoing...":"Upcoming..."}</h2><p>{canceled?"No consultation information is available for this canceled appointment.":ongoing?"Consultation information is being recorded and will update after completion.":"Consultation details will be available once the session begins."}</p><article><small>Reason for Visit</small><b>{appointment.reason||"No reason for visit recorded."}</b></article></div>}</section></main></HospitalChrome>;
}
function CompletedDetails({item}) { const consultation=item.consultation||{};return <div className="completed-consultation"><section><Info title="Reason for Visit" value={item.reason||"Not recorded"}/><Info title="Diagnosed With" value={consultation.diagnosis||"Not recorded"}/><Info title="Clinician Report" value={consultation.report||"Not recorded"}/><Info title="Lab Tests / Investigations" value={(consultation.labs||[]).map(l=>l.name).join(", ")||"No lab tests recorded"}/></section><section><Info title="Vitals" value={consultation.vitals?Object.entries(consultation.vitals).map(([k,v])=>`${k}: ${v}`).join(" · "):"No vitals recorded"}/><Info title="Prescriptions / Medication" value={(consultation.medications||[]).map(m=>m.name).join(", ")||"No medication recorded"}/></section></div>}
function Info({title,value}) {return <article><h3>{title}</h3><p>{value}</p></article>}
