import { useEffect, useState } from "react";
import { formatDate, formatTime } from "../hospitalData";
import { hospitalApi } from "../../hospitalApi";
import { mapFacilityAppointment } from "../home/useFacilityOperations";

const states = ["PENDING","UPCOMING","DECLINED","EXPIRED"];
const patientFor = (data,item) => data.patients.find(patient => (patient.name || `${patient.firstName} ${patient.lastName}`).toLowerCase() === item.patient?.toLowerCase());

export default function PendingRequests({ appointments = [], onChange = () => {} }) {
  const [options,setOptions]=useState({patients:[],clinicians:[]});
  useEffect(()=>{let live=true;hospitalApi.appointmentOptions().then(result=>{if(live)setOptions(result)}).catch(()=>{});return()=>{live=false}},[]);
  const data={appointments,patients:options.patients||[],staff:(options.clinicians||[]).map(item=>({...item,id:item.membershipId,role:item.role}))};
  const updateAppointment=async(id,change)=>{const doctor=data.staff.find(item=>item.name===change.clinician);const payload={...(change.status?{status:change.status==="UPCOMING"?"CONFIRMED":change.status}:{}),...(change.start?{date:new Date(change.start).toISOString()}:{}),...(doctor?{clinicianMembershipId:doctor.membershipId}:{})};const result=await hospitalApi.updateAppointment(id,payload);const item=mapFacilityAppointment(result.appointment);onChange(current=>current.map(existing=>existing.id===id?item:existing));};
  const pending = data.appointments.filter(item=>item.status==="PENDING");
  const history = data.appointments.filter(item=>["DECLINED","EXPIRED"].includes(item.status));
  const [flow,setFlow]=useState(null); const [selected,setSelected]=useState(null); const [doctor,setDoctor]=useState(""); const [result,setResult]=useState(null);
  const doctors=data.staff.filter(person=>["GENERALIST","SPECIALIST","DOCTOR"].includes(person.role));
  const stats=[["Total",data.appointments.length],["Pending Request",pending.length],["Accepted",data.appointments.filter(i=>i.status==="UPCOMING").length],["Declined",history.filter(i=>i.status==="DECLINED").length],["Expired",history.filter(i=>i.status==="EXPIRED").length]];
  const open=(item,next)=>{setSelected(item);setFlow(next)};
  const accept=()=>{if(!doctor)return setResult("failed");updateAppointment(selected.id,{status:"UPCOMING",clinician:doctor,acceptedAt:new Date().toISOString()});setResult("success")};
  return <><section className="request-stats"><h2>Today’s Appointment Request Stat</h2><div>{stats.map(([label,value])=><article key={label}><span>{label}</span><b>{value}</b></article>)}</div></section><section className="pending-request-section"><h2>Pending Request <b>{pending.length}</b></h2>{pending.length===0?<div className="appointment-empty"><span>▣</span><h3>No pending requests</h3><p>New appointment requests will appear here.</p></div>:<div className="pending-request-grid">{pending.map(item=><article key={item.id}><h3><i>{item.patient?.[0]}</i>{item.patient}<small>{item.type||"Consultation"}</small></h3><p>{formatDate(item.start)} <b>{formatTime(item.start)}</b></p><div><small>Visit Reason</small>{item.reason||"No reason recorded"}</div><footer><button onClick={()=>open(item,"request")}>Accept</button><button onClick={()=>open(item,"decline")}>Decline</button></footer></article>)}</div>}</section><section className="request-history"><h2>Request History</h2>{history.length===0?<div className="appointment-empty"><h3>No request history</h3><p>Declined and expired requests will appear here.</p></div>:<div className="pending-request-grid">{history.map(item=><button key={item.id} onClick={()=>open(item,"history")}><h3>{item.patient}<small>{item.type||"Consultation"}</small></h3><em>{item.status}</em><p>{item.reason||"No reason recorded"}</p><time>{formatDate(item.start)} {formatTime(item.start)}</time></button>)}</div>}</section>
  {flow&&selected&&<Workflow type={flow} item={selected} patient={patientFor(data,selected)} doctors={doctors} doctor={doctor} setDoctor={setDoctor} close={()=>setFlow(null)} next={setFlow} accept={accept} updateAppointment={updateAppointment} setResult={setResult}/>} {result&&<Result type={result} close={()=>{setResult(null);setFlow(null);setSelected(null)}} retry={()=>setResult(null)}/>}</>;
}

function Workflow({type,item,patient,doctors,doctor,setDoctor,close,next,accept,updateAppointment,setResult}) {
 const [reason,setReason]=useState("");const [note,setNote]=useState("");const [newStart,setNewStart]=useState("");
 const summary=<div className="request-summary"><p><span>Patient</span><b>{item.patient}</b></p><p><span>Appointment Type</span><b>{item.type||"Consultation"}</b></p><p><span>Previous Date & Time</span><b>{formatDate(item.start)} {formatTime(item.start)}</b></p></div>;
 if(type==="request")return <Modal close={close}><h2>{item.patient}</h2><p className="request-time">Scheduled Appointment Date and Time <b>{formatDate(item.start)} {formatTime(item.start)}</b></p><div className="request-actions"><button onClick={()=>next("assign")}>Accept</button><button onClick={()=>next("decline")}>Decline</button><button onClick={()=>next("reschedule")}>Reschedule</button></div><Info item={item} patient={patient}/></Modal>;
 if(type==="assign"||type==="confirm")return <Modal close={close}><h2>{type==="assign"?"Select and Assign a Doctor to Confirm Patient Acceptance":"Appointment Rescheduling Confirmation"}</h2>{summary}<label className="workflow-label">Assign Doctor to Patient<select value={doctor} onChange={e=>setDoctor(e.target.value)}><option value="">Select Doctor</option><option>Open to Available Generalist</option>{doctors.map(d=><option key={d.id} value={d.name}>{d.name} — {d.role}</option>)}</select></label><div className="doctor-list">{doctors.length===0?<p>No doctors available</p>:doctors.map(d=><button className={doctor===d.name?"selected":""} key={d.id} onClick={()=>setDoctor(d.name)}><i>{d.name?.[0]}</i><b>{d.name}</b><small>{d.role}</small></button>)}</div><footer className="workflow-footer"><button onClick={close}>Back</button><button onClick={accept}>Confirm</button></footer></Modal>;
 if(type==="decline")return <Modal close={close}><h2>Decline Appointment Request</h2><p>Are you sure you want to decline this appointment request?</p>{summary}<label className="workflow-label">Reason for Decline<select value={reason} onChange={e=>setReason(e.target.value)}><option value="">Select Reason</option><option>Doctor Unavailable</option><option>Incomplete Information</option><option>Not Within Department Scope</option><option>Others</option></select></label><label className="workflow-label">Additional Information (Optional)<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Type here"/></label><footer className="workflow-footer"><button className="decline" onClick={()=>{if(!reason)return;updateAppointment(item.id,{status:"DECLINED",declineReason:reason,declineNote:note,declinedAt:new Date().toISOString()});close()}}>Yes, Decline</button><button onClick={close}>Cancel</button></footer></Modal>;
 if(type==="reschedule")return <Modal close={close} wide><h2>Reschedule and Accept Appointment</h2>{summary}<label className="workflow-label">Select New Date & Time<input type="datetime-local" value={newStart} onChange={e=>setNewStart(e.target.value)}/></label><footer className="workflow-footer"><button onClick={close}>Cancel</button><button onClick={()=>{if(!newStart)return;updateAppointment(item.id,{start:newStart,end:new Date(new Date(newStart).getTime()+30*60000).toISOString()});next("assign")}}>Next</button></footer></Modal>;
 return <HistoryModal item={item} patient={patient} close={close}/>;
}
function Modal({children,close,wide}) {return <div className="screen-overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><section className={`request-modal ${wide?"wide":""}`}><button className="preview-close" onClick={close}>×</button>{children}</section></div>}
function Info({item,patient}) {return <div className="request-info"><article><h3>Reason for Visit</h3><p>{item.reason||"No reason recorded"}</p></article><article><h3>Patient Health Summary</h3><div>{[["Age",patient?.age],["Gender",patient?.gender],["Blood Type",patient?.bloodType],["Weight",patient?.weight],["Height",patient?.height],["BP",patient?.bloodPressure]].map(([k,v])=><span key={k}>{k}<b>{v||"—"}</b></span>)}</div></article></div>}
function HistoryModal({item,patient,close}) {const declined=item.declinedAt?new Date(item.declinedAt):null;const details=[["Age",patient?.age],["Gender",patient?.gender],["Blood Type",patient?.bloodType],["Weight",patient?.weight],["Height",patient?.height],["BP",patient?.bloodPressure],["Smoke",patient?.smoke],["Alcohol",patient?.alcohol]];return <Modal close={close} wide><div className="history-profile"><i>{patient?.avatar?<img src={patient.avatar} alt=""/>:item.patient?.[0]}</i><div><h2>{item.patient}</h2><small>{item.type||"Consultation"}</small></div><dl><div><dt>Status</dt><dd>{item.status}</dd></div><div><dt>By</dt><dd><b>{item.declinedBy||"Facility Admin"}</b><small>{item.declinedByRole||"Receptionist"}</small></dd></div><div><dt>Appointment Date & Time</dt><dd>{formatTime(item.start)} &nbsp; {formatDate(item.start)}</dd></div><div><dt>Declined Date & Time</dt><dd>{declined?`${formatTime(declined)}  ${formatDate(declined)}`:"—"}</dd></div></dl></div><section className="history-decline"><h3>Reason for Decline</h3><article><b>{item.declineReason||"Reason not recorded"}</b><p>{item.declineNote||"No additional information was provided."}</p></article></section><section className="history-visit"><h3>Reason for Visit</h3><p>{item.reason||"No reason recorded"}</p><h3>Patient Health Summary</h3><div>{details.map(([label,value])=><span key={label}><small>{label}</small><b>{value||"—"}</b></span>)}</div></section></Modal>}
function Result({type,close,retry}) {const failed=type==="failed";return <div className="screen-overlay"><section className="workflow-result"><i>{failed?"!":"✓"}</i><h2>{failed?"Acceptance Failed":"Successfully"}</h2><p>{failed?"We couldn’t complete this request. Select a doctor and try again.":"Appointment request accepted and doctor assigned to patient"}</p>{failed&&<button onClick={retry}>Try Again</button>}<button className={failed?"secondary":""} onClick={close}>{failed?"Back":"Done"}</button></section></div>}
