import { useMemo, useState } from "react";
import HospitalChrome from "../HospitalChrome";
import { formatDate, formatTime, useHospitalData } from "../hospitalData";

function Empty({ title, text, action, onAction }) { return <div className="dashboard-empty"><span>◇</span><h3>{title}</h3><p>{text}</p>{action && <button onClick={onAction}>{action}</button>}</div>; }

function AppointmentForm({ onClose, onSave }) {
  const [form, setForm] = useState({ patient: "", clinician: "", start: "", end: "", reason: "", status: "UPCOMING" });
  const [error, setError] = useState("");
  const field = (key) => (event) => setForm({ ...form, [key]: event.target.value });
  return <div className="entry-overlay" onMouseDown={onClose}><form className="entry-modal" onMouseDown={(event) => event.stopPropagation()} onSubmit={(event) => { event.preventDefault(); if (!form.patient || !form.clinician || !form.start || !form.end) return setError("Patient, clinician, start and end time are required"); onSave(form); onClose(); }}><button type="button" className="entry-close" onClick={onClose}>×</button><h2>Add appointment</h2><p>Saved appointments populate the dashboard and calendar automatically.</p><label>Patient name<input value={form.patient} onChange={field("patient")} placeholder="Enter patient name" /></label><label>Clinician<input value={form.clinician} onChange={field("clinician")} placeholder="Enter clinician name" /></label><div><label>Starts<input type="datetime-local" value={form.start} onChange={field("start")} /></label><label>Ends<input type="datetime-local" value={form.end} onChange={field("end")} /></label></div><label>Visit reason<textarea value={form.reason} onChange={field("reason")} placeholder="Optional visit reason" /></label>{error && <small className="entry-error">{error}</small>}<button className="save-entry">Save appointment</button></form></div>;
}

export default function HospitalHome({ go }) {
  const { data, addAppointment, updateAppointment } = useHospitalData(); const [adding, setAdding] = useState(false);
  const upcoming = useMemo(() => data.appointments.filter((item) => item.status === "UPCOMING" && new Date(item.end) >= new Date()).sort((a,b) => new Date(a.start)-new Date(b.start)), [data.appointments]);
  const pending = data.appointments.filter((item) => item.status === "PENDING");
  const stats = { total: data.appointments.length, upcoming: upcoming.length, completed: data.appointments.filter((item) => item.status === "COMPLETED").length, rescheduled: data.appointments.filter((item) => item.status === "RESCHEDULED").length, missed: data.appointments.filter((item) => item.status === "MISSED").length, canceled: data.appointments.filter((item) => item.status === "CANCELED").length };
  return <HospitalChrome title="Home" active="home" go={go} onAdd={() => setAdding(true)}><div className="dashboard"><section className="overview panel"><h2>Overview</h2><div>{[["Total Patients", data.patients.length], ["Generalist (Doctor)", data.staff.filter(s => s.role === "GENERALIST").length], ["Specialists (Doctor)", data.staff.filter(s => s.role === "SPECIALIST").length], ["Receptionist", data.staff.filter(s => s.role === "RECEPTIONIST").length], ["Pending Invitation", data.staff.filter(s => s.status === "INVITED").length]].map(([label,value]) => <article key={label}><span>{label}</span><b>{value}</b></article>)}</div></section><section className="dashboard-section"><header><h2>Upcoming Appointment</h2><button onClick={() => go("calendar")}>Open calendar</button></header>{upcoming.length ? <div className="upcoming-grid">{upcoming.slice(0,4).map((item) => <article key={item.id}><h3><i>{item.patient[0]}</i>{item.patient}<small>{item.reason || "Appointment"}</small></h3><div><b>{formatDate(item.start)}</b><span>{formatTime(item.start)} to {formatTime(item.end)}</span></div><button onClick={() => go("calendar")}>View Details</button></article>)}</div> : <Empty title="No upcoming appointments" text="Appointments created for future dates will appear here." action="Add appointment" onAction={() => setAdding(true)} />}</section><section className="panel pending-panel"><header><h2>Pending Appointment Request <b>{pending.length}</b></h2></header>{pending.length ? <div className="pending-grid">{pending.map((item) => <article key={item.id}><h3>{item.patient}<small>{item.reason || "Appointment request"}</small></h3><p>{formatDate(item.start)} · {formatTime(item.start)}</p><div><button onClick={() => updateAppointment(item.id,"UPCOMING")}>Accept</button><button className="decline" onClick={() => updateAppointment(item.id,"CANCELED")}>Decline</button></div></article>)}</div> : <Empty title="No pending appointment requests" text="New patient appointment requests will appear here for review." />}</section><section className="panel stats"><h2>Today’s Appointment Stat</h2><div>{Object.entries(stats).map(([key,value]) => <article key={key}><span>{key[0].toUpperCase()+key.slice(1)}</span><b>{value}</b></article>)}</div></section><section className="tasks"><div><h2>Tasks & Alerts</h2><Empty title="No tasks or alerts" text="Referral requests, reminders, and clinical tasks will appear here." /></div><div className="completion"><b>0%</b><span><strong>Set up your hospital workspace</strong>Add staff and appointments to begin.</span></div></section></div>{adding && <AppointmentForm onClose={() => setAdding(false)} onSave={addAppointment} />}</HospitalChrome>;
}
