import { useEffect, useMemo, useState } from "react";
import HospitalChrome from "../HospitalChrome";
import { formatDate, formatTime } from "../hospitalData";
import { hospitalApi } from "../../hospitalApi";

const normalize = (value) => String(value || "").trim().toUpperCase().replace(/[ -]+/g, "_");
const pendingStatuses = new Set(["PENDING", "PENDING_REQUEST", "REQUESTED"]);
const shown = (value, fallback = "Not recorded") => value === undefined || value === null || value === "" ? fallback : value;
const Empty = ({ text }) => <div className="referral-detail-empty">{text}</div>;
const Avatar = ({ image, name }) => image ? <img src={image} alt=""/> : <i>{name?.[0] || "?"}</i>;
const Modal = ({ children, close, className = "" }) => <div className="referral-modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && close()}><section className={`referral-modal ${className}`}><button className="referral-modal-close" onClick={close}>×</button>{children}</section></div>;

function AssignModal({ referral, doctors, close, save }) {
  const [doctorId, setDoctorId] = useState("");
  const name = referral.patientName || referral.patient?.name || referral.patient || "Patient name not recorded";
  const image = referral.patientImage || referral.patient?.image || referral.patient?.avatar;
  return <Modal close={close}><header><h2>Accept Referral Request</h2><p>You are about to accept a referral. Please assign a doctor to the patient.</p></header><div className="assignment-patient"><Avatar image={image} name={name}/><span><strong>{name}</strong><small>Patient</small></span></div><label>Assign Doctor<select value={doctorId} onChange={(event) => setDoctorId(event.target.value)}><option value="">{doctors.length ? "Select Doctor" : "No doctors available"}</option>{doctors.map((doctor) => <option value={doctor.id} key={doctor.id}>{doctor.name}{doctor.specialty ? ` — ${doctor.specialty}` : ""}</option>)}</select></label><footer><button onClick={close}>Cancel</button><button disabled={!doctorId} onClick={() => save(doctors.find((doctor) => doctor.id === doctorId))}>Confirm</button></footer></Modal>;
}

function ScheduleModal({ referral, close, save }) {
  const initial = referral.appointmentAt || referral.scheduledAt;
  const [date, setDate] = useState(initial ? new Date(initial).toISOString().slice(0, 10) : "");
  const [time, setTime] = useState(initial ? new Date(initial).toTimeString().slice(0, 5) : "");
  const valid = date && time && new Date(`${date}T${time}`) > new Date();
  return <Modal close={close} className="schedule-referral-modal"><header><h2>Reschedule Appointment to Confirm</h2><p>Schedule a date and time for the appointment to confirm referral acceptance.</p></header><div className="schedule-fields"><label>Select New Date<input type="date" min={new Date().toISOString().slice(0, 10)} value={date} onChange={(event) => setDate(event.target.value)}/></label><label>Available Time<input type="time" value={time} onChange={(event) => setTime(event.target.value)}/></label></div><footer><button onClick={close}>Cancel</button><button disabled={!valid} onClick={() => save(new Date(`${date}T${time}`).toISOString())}>Confirm</button></footer></Modal>;
}

function SuccessModal({ date, close }) { return <Modal close={close} className="schedule-success"><span className="success-check">✓</span><h2>Appointment Successfully Scheduled</h2><p>The patient is expected to arrive at your facility on the scheduled date.</p><div><small>Appointment Date and Time</small><strong>{formatDate(date)}</strong><i/><strong>{formatTime(date)}</strong></div><button onClick={close}>Done</button></Modal>; }

export default function ReferralDetails({ go }) {
  const id=sessionStorage.getItem("selectedReferralId");const[referral,setReferral]=useState(null);const[staff,setStaff]=useState([]);const[loading,setLoading]=useState(true);const[loadError,setLoadError]=useState("");
  useEffect(()=>{let live=true;Promise.all([hospitalApi.getReferral(id),hospitalApi.appointmentOptions()]).then(([result,options])=>{if(!live)return;const item=result.referral;setReferral({...item,patientName:item.patient,fromName:item.fromClinician,toName:item.toClinician,fromFacility:item.sendingFacility,appointmentAt:item.appointment?.date});setStaff((options.clinicians||[]).map(person=>({...person,id:person.membershipId,specialty:person.jobTitle})));}).catch(reason=>{if(live)setLoadError(reason.message)}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[id]);
  const [dialog, setDialog] = useState(null);
  const [menu, setMenu] = useState(false);
  const doctors = useMemo(() => staff.filter((person) => ["DOCTOR", "GENERALIST", "SPECIALIST", "CLINICIAN"].includes(normalize(person.role))), [staff]);
  if(loading)return <HospitalChrome title="Incoming Referral" active="referrals" go={go}><main className="referral-details-page"><section className="referral-details-missing"><h2>Loading referral</h2></section></main></HospitalChrome>;
  if (!referral) return <HospitalChrome title="Incoming Referral" active="referrals" go={go}><main className="referral-details-page"><section className="referral-details-missing"><h2>Referral not found</h2><p>{loadError||"The selected referral is unavailable or has been removed."}</p><button onClick={() => go("referrals")}>Back to referrals</button></section></main></HospitalChrome>;

  const patient = typeof referral.patient === "object" ? referral.patient : {};
  const name = referral.patientName || patient.name || referral.patient || "Patient name not recorded";
  const image = referral.patientImage || patient.image || patient.avatar;
  const status = normalize(referral.status) || "PENDING";
  const pending = pendingStatuses.has(status);
  const date = referral.appointmentAt || referral.scheduledAt || referral.date || referral.createdAt;
  const health = referral.healthSummary || patient.healthSummary || patient.health || {};
  const facts = [["Age", referral.patientAge || patient.age, "Yrs"], ["Gender", referral.patientGender || patient.gender], ["Blood Type", health.bloodType], ["Weight", health.weight, health.weight ? "kg" : ""], ["Height", health.height, health.height ? "cm" : ""], ["BP", health.bloodPressure || health.bp], ["Smoke", health.smokes], ["Alcohol", health.alcohol]];
  const documents = referral.documents || referral.attachments || [];
  const facility = referral.fromFacility || referral.referringFacility;
  const referrer = referral.from || referral.referrer || {};
  const assigned = staff.find((doctor) => doctor.id === (referral.toId || referral.assignedDoctorId)) || referral.assignedDoctor || referral.to;
  const timeline = referral.trackingHistory || referral.referralHistory || [];
  const decline = referral.decline || {};
  const act=async(action)=>{const result=await hospitalApi.updateReferral(referral.id,action);setReferral(current=>({...current,...result.referral,patientName:result.referral.patient,fromName:result.referral.fromClinician,toName:result.referral.toClinician,fromFacility:result.referral.sendingFacility,appointmentAt:result.referral.appointment?.date}))};
  const accept = async (doctor) => { if (!doctor) return; await act("accept"); setDialog(null); };
  const schedule = async (appointmentAt) => { const result=await hospitalApi.updateReferral(referral.id,{action:"accept",scheduledAt:appointmentAt});setReferral(current=>({...current,...result.referral,patientName:result.referral.patient,fromName:result.referral.fromClinician,toName:result.referral.toClinician,fromFacility:result.referral.sendingFacility,appointmentAt:result.referral.appointment?.date}));setDialog({ type: "success", date: appointmentAt }); };

  return <HospitalChrome title="Incoming Referral" active="referrals" go={go}><main className="referral-details-page"><button className="referral-details-back" onClick={() => go("referrals")}>←</button><section className="referral-detail-hero"><div className="detail-patient"><Avatar image={image} name={name}/><span><h2>{name}</h2><p>Referred Patient</p></span></div>{date && <div className="detail-date"><b>{formatDate(date)}</b><span/><b>{formatTime(date)}</b></div>}<dl><div><dt>Referral ID</dt><dd>{shown(referral.referralId || referral.reference)}</dd></div><div><dt>Insurance Provider</dt><dd>{shown(referral.insuranceProvider || patient.insurance?.provider)}</dd></div><div><dt>Insurance Policy Number</dt><dd>{shown(referral.insurancePolicyNumber || patient.insurance?.policyNumber)}</dd></div><div><dt>Referral Date</dt><dd>{date ? `${formatTime(date)} ${formatDate(date)}` : "Not recorded"}</dd></div><div><dt>Status</dt><dd><em className={`detail-status ${status.toLowerCase()}`}>{status.replaceAll("_", " ")}</em></dd></div><div><dt>Priority Level</dt><dd><em className={`detail-priority ${normalize(referral.priority).toLowerCase()}`}>{shown(referral.priority, "Routine")}</em></dd></div></dl>{pending && <div className="detail-actions"><button onClick={() => setDialog({ type: "assign" })}>Accept Referral</button><button onClick={() => act("decline")}>Decline</button><span><button onClick={() => setMenu(!menu)}>•••</button>{menu && <button className="detail-more-menu" onClick={() => { setMenu(false); setDialog({ type: "schedule" }); }}>Accept and Reschedule</button>}</span></div>}</section>
    <section className="health-summary"><h2>Patient Health Summary</h2><div>{facts.map(([label, fact, unit]) => <article key={label}><small>{label}</small><strong>{shown(fact)}{fact && unit ? <i>{unit}</i> : null}</strong></article>)}</div></section><section className="clinical-summary"><div><h3>Primary Complaint</h3><p>{shown(referral.primaryComplaint || referral.reason || referral.referralReason)}</p><h3>Additional Information</h3><p>{shown(referral.additionalInformation)}</p></div><div><h3>Clinical Notes</h3><p>{shown(referral.clinicalNotes)}</p></div></section>
    <div className="referral-detail-columns"><section><h3>{status === "MULTI_REFERRAL" ? "Track Referral" : "Referring Facility"}</h3>{status === "MULTI_REFERRAL" ? timeline.length ? <ol className="referral-timeline">{timeline.map((entry, index) => <li key={entry.id || index}><strong>{shown(entry.facilityName || entry.facility?.name)}</strong><small>{shown(entry.facilityAddress || entry.facility?.address)}</small><span>{shown(entry.doctorName || entry.doctor?.name)}</span>{entry.date && <time>{formatTime(entry.date)} {formatDate(entry.date)}</time>}</li>)}</ol> : <Empty text="No referral tracking history recorded."/> : facility || Object.keys(referrer).length ? <div className="facility-card"><strong>{shown(facility?.name || referral.facilityName)}</strong><small>{shown(facility?.address || referral.facilityAddress)}</small><hr/><span>{shown(referrer.name || referral.fromName || referral.referringClinician)}</span><small>{shown(referrer.specialty)}</small></div> : <Empty text="No referring facility information recorded."/>}</section><section><h3>Attached Document</h3>{documents.length ? <div className="document-list">{documents.map((document, index) => <a href={document.url || document.link} target="_blank" rel="noreferrer" key={document.id || index}><i>▤</i><span><strong>{shown(document.name || document.title, "Document")}</strong><small>{shown(document.type || document.format, "File")}</small></span></a>)}</div> : <Empty text="No documents attached."/>}</section></div>
    {status === "ACCEPTED" && <section className="assigned-section"><h3>Assigned Doctor</h3>{assigned ? <div><Avatar image={assigned.image || assigned.avatar} name={assigned.name || referral.toName}/><span><strong>{shown(assigned.name || referral.toName)}</strong><small>{shown(assigned.specialty || assigned.role)}</small></span></div> : <Empty text="No doctor assigned."/>}</section>}{status === "DECLINED" && <section className="decline-section"><h3>Declined by</h3><strong>{shown(decline.doctorName || referral.declinedByName)}</strong><small>{referral.declinedAt ? `${formatTime(referral.declinedAt)} ${formatDate(referral.declinedAt)}` : "Date not recorded"}</small><h3>Reason for Decline</h3><p><b>{shown(decline.category || referral.declineReason)}</b><span>{shown(decline.notes || referral.declineNotes)}</span></p></section>}{pending && <section className="access-restricted"><b>Access Restricted</b><span>Access to patient medical records will be available to the attending doctor.</span></section>}
    {dialog?.type === "assign" && <AssignModal referral={referral} doctors={doctors} close={() => setDialog(null)} save={accept}/>} {dialog?.type === "schedule" && <ScheduleModal referral={referral} close={() => setDialog(null)} save={schedule}/>} {dialog?.type === "success" && <SuccessModal date={dialog.date} close={() => { setDialog(null); go("referrals"); }}/>}</main></HospitalChrome>;
}
