import { useMemo, useState } from "react";
import HospitalChrome from "../HospitalChrome";
import { useHospitalData } from "../hospitalData";

const shown = (value) => value || "Not recorded";
const Avatar = ({ person }) => person?.image || person?.avatar ? <img src={person.image || person.avatar} alt=""/> : <i>{person?.name?.[0] || "?"}</i>;

export default function MessageCenter({ go }) {
  const { data, sendMessage } = useHospitalData(); const [query, setQuery] = useState(""); const [selectedId, setSelectedId] = useState(data.staff[0]?.id || null); const [text, setText] = useState(""); const [attachment, setAttachment] = useState(null); const [attachOpen, setAttachOpen] = useState(false);
  const staff = data.staff.filter((item) => item.name?.toLowerCase().includes(query.toLowerCase())); const selected = data.staff.find((item) => item.id === selectedId);
  const messages = useMemo(() => data.messages.filter((item) => item.staffId === selectedId || item.recipientId === selectedId || item.senderId === selectedId).sort((a, b) => new Date(a.createdAt) - new Date(b.createdAt)), [data.messages, selectedId]);
  const send = () => { if ((!text.trim() && !attachment) || !selectedId) return; sendMessage({ staffId: selectedId, recipientId: selectedId, sender: "FACILITY", content: text.trim(), attachment: attachment ? { name: attachment.name, type: attachment.type, size: attachment.size } : null }); setText(""); setAttachment(null); };
  return <HospitalChrome title="Message" active="messages" go={go}><main className="message-page"><aside className="message-contacts"><header><h2>Staff Members</h2><small>All ({data.staff.length}) staff members</small></header><label>⌕<input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search by Name"/></label>{staff.length ? <div>{staff.map((item) => { const last = data.messages.filter((message) => message.staffId === item.id || message.recipientId === item.id || message.senderId === item.id).at(-1); return <button className={selectedId === item.id ? "active" : ""} onClick={() => setSelectedId(item.id)} key={item.id}><Avatar person={item}/><span><b>{shown(item.name)}</b><small>{last?.content || (last?.attachment ? last.attachment.name : "No messages yet")}</small></span>{last && <time>{new Date(last.createdAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</time>}</button>; })}</div> : <section className="message-empty small"><i>♙</i><h3>{data.staff.length ? "No staff found" : "No staff members"}</h3><p>{data.staff.length ? "Try another name." : "Add staff before starting a conversation."}</p></section>}</aside><section className="conversation">{selected ? <><header><Avatar person={selected}/><span><b>{selected.name}</b><small>{selected.status || "Status not recorded"}</small></span></header><div className="message-thread">{messages.length ? messages.map((message) => <article className={message.sender === "FACILITY" ? "sent" : "received"} key={message.id}>{message.content && <p>{message.content}</p>}{message.attachment && <a href={message.attachment.url}>{message.attachment.type?.startsWith("image/") ? "▧" : "▤"} {message.attachment.name}</a>}<time>{new Date(message.createdAt).toLocaleString()}</time></article>) : <section className="message-empty"><i>▰</i><h3>No messages yet</h3><p>Send a message to begin this conversation.</p></section>}</div><footer><span>{attachOpen && <div className="attachment-menu"><label>▤ Document<input type="file" onChange={(e) => { setAttachment(e.target.files?.[0] || null); setAttachOpen(false); }}/></label><label>▧ Photo & Video<input type="file" accept="image/*,video/*" onChange={(e) => { setAttachment(e.target.files?.[0] || null); setAttachOpen(false); }}/></label></div>}<button onClick={() => setAttachOpen(!attachOpen)}>＋</button></span>{attachment && <em>{attachment.name}<button onClick={() => setAttachment(null)}>×</button></em>}<input value={text} onChange={(e) => setText(e.target.value)} onKeyDown={(e) => e.key === "Enter" && send()} placeholder="Type a message"/><button onClick={send}>➤</button></footer></> : <section className="message-empty"><i>▰</i><h3>Select a staff member</h3><p>Choose a staff member to view or begin a conversation.</p></section>}</section></main></HospitalChrome>;
}
