import { useMemo, useState } from "react";
import HospitalChrome from "../HospitalChrome";
import { useHospitalData } from "../hospitalData";

export default function NotificationCenter({ go }) {
  const { data, updateNotification, deleteNotification } = useHospitalData(); const [filter, setFilter] = useState("ALL"); const [selectedId, setSelectedId] = useState(null); const [menuId, setMenuId] = useState(null);
  const notifications = useMemo(() => data.notifications.filter((item) => filter === "ALL" || (filter === "READ" ? item.read : !item.read)).sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt)), [data.notifications, filter]); const selected = data.notifications.find((item) => item.id === selectedId);
  const open = (item) => { setSelectedId(item.id); if (!item.read) updateNotification(item.id, { read: true, readAt: new Date().toISOString() }); };
  return <HospitalChrome title="Notification" active="notifications" go={go}><main className="notification-page"><aside><header><h2>Notification</h2><small>All ({data.notifications.length}) notifications</small></header><nav>{["ALL", "READ", "UNREAD"].map((item) => <button className={filter === item ? "active" : ""} onClick={() => setFilter(item)} key={item}>{item[0] + item.slice(1).toLowerCase()}</button>)}</nav>{notifications.length ? <div className="notification-list">{notifications.map((item) => <article className={!item.read ? "unread" : ""} key={item.id} onClick={() => open(item)}><i>{item.icon || "ⓘ"}</i><span><b>{item.title || "Notification"}</b><p>{item.preview || item.message || "No preview available."}</p><time>{item.createdAt ? new Date(item.createdAt).toLocaleString() : "Date not recorded"}</time></span><button onClick={(e) => { e.stopPropagation(); setMenuId(menuId === item.id ? null : item.id); }}>⋮</button>{menuId === item.id && <div className="notification-menu"><button onClick={(e) => { e.stopPropagation(); updateNotification(item.id, { read: true }); setMenuId(null); }}>Mark as Read</button><button onClick={(e) => { e.stopPropagation(); deleteNotification(item.id); if (selectedId === item.id) setSelectedId(null); }}>Delete</button></div>}</article>)}</div> : <section className="notification-empty"><i>♟</i><h3>{data.notifications.length ? `No ${filter.toLowerCase()} notifications` : "No notifications yet"}</h3><p>{data.notifications.length ? "Choose another filter." : "Hospital updates and alerts will appear here."}</p></section>}</aside><section className="notification-detail">{selected ? <article><header><i>{selected.icon || "ⓘ"}</i><h2>{selected.title || "Notification"}</h2><time>{selected.createdAt ? new Date(selected.createdAt).toLocaleString() : "Date not recorded"}</time></header><div className="notification-body">{selected.contentBlocks?.length ? selected.contentBlocks.map((block, index) => block.type === "heading" ? <h3 key={index}>{block.text}</h3> : block.type === "link" ? <a href={block.url} key={index}>{block.text || block.url}</a> : <p key={index}>{block.text}</p>) : <p>{selected.message || selected.body || "No notification details available."}</p>}</div>{selected.attachment && <a className="notification-attachment" href={selected.attachment.url} target="_blank" rel="noreferrer"><i>▤</i><span><b>{selected.attachment.name || "Attachment"}</b><small>{selected.attachment.type || "Document"}</small></span><em>View</em></a>}</article> : <section className="notification-empty"><i>ⓘ</i><h3>Select a notification</h3><p>Choose a notification to read its details.</p></section>}</section></main></HospitalChrome>;
}
