import { useEffect, useMemo, useState } from "react";
import HospitalChrome from "../HospitalChrome";
import { hospitalApi } from "../../hospitalApi";

const norm = (value) => String(value || "").toUpperCase();
const roleType = (staff) => norm(staff.role);

export default function StaffManagement({ go }) {
  const [records,setRecords]=useState({staff:[],invitations:[]});
  const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const [query,setQuery]=useState(""); const [filter,setFilter]=useState("ALL"); const [page,setPage]=useState(1); const size=6;
  useEffect(()=>{let current=true;hospitalApi.listStaff().then(value=>current&&setRecords(value)).catch(next=>current&&setError(next.message)).finally(()=>current&&setLoading(false));return()=>{current=false}},[]);
  const rows=useMemo(()=>[...records.staff,...records.invitations.map(invitation=>({id:`invite:${invitation.id}`,name:invitation.email,email:invitation.email,role:invitation.role,status:"INVITED",joinedAt:invitation.createdAt,pendingInvitation:true}))],[records]);
  const staff=useMemo(()=>rows.filter(item=>{const match=`${item.name||""} ${item.staffId||item.id||""}`.toLowerCase().includes(query.toLowerCase());return match&&(filter==="ALL"||(filter==="SUSPENDED"?norm(item.status)===filter:roleType(item).includes(filter))) }),[rows,query,filter]);
  const pages=Math.max(1,Math.ceil(staff.length/size)); const visible=staff.slice((page-1)*size,page*size);
  const stats=[["Total Staff",records.staff.length],["Active Staff",records.staff.filter(item=>norm(item.status)==="ACTIVE").length],["Pending Invite",records.invitations.length],["Suspended Staff",records.staff.filter(item=>norm(item.status)==="SUSPENDED").length],["Admin",records.staff.filter(item=>roleType(item).includes("ADMIN")).length],["Specialist Doctors",records.staff.filter(item=>roleType(item).includes("SPECIALIST")).length],["Generalist Doctors",records.staff.filter(item=>roleType(item).includes("GENERALIST")).length],["Receptionist",records.staff.filter(item=>roleType(item).includes("RECEPTION")).length]];
  const open=item=>{if(item.pendingInvitation)return;sessionStorage.setItem("selectedStaffId",item.id);go("staff-profile")};
  return <HospitalChrome title="Staff Management" active="staff-management" go={go}><main className="staff-page"><header className="staff-tools"><label>⌕<input value={query} onChange={event=>{setQuery(event.target.value);setPage(1)}} placeholder="Search by Name or ID"/></label><div><button onClick={()=>go("invite-staff")}>Add Existing User</button><button onClick={()=>go("add-staff")}>＋ Add Staff</button></div></header><section className="staff-stats">{stats.map(([label,count])=><article key={label}><i>♙</i><span>{label}<b>{count}</b></span></article>)}</section><section className="staff-list"><h2>All Your Staff</h2><nav>{["ALL","SPECIALIST","GENERALIST","RECEPTION","SUSPENDED"].map(item=><button className={filter===item?"active":""} onClick={()=>{setFilter(item);setPage(1)}} key={item}>{item[0]+item.slice(1).toLowerCase()}</button>)}</nav>{error&&<div className="staff-empty"><h3>Unable to load staff</h3><p>{error}</p></div>}{!error&&loading&&<div className="staff-empty"><p>Loading staff…</p></div>}{!error&&!loading&&(visible.length?<div className="staff-table"><header><span>Name</span><span>Department</span><span>Role</span><span>Emp Type</span><span>Status</span><span>Joined</span><span/></header>{visible.map(item=><article key={item.id}><div className="staff-name"><i>{item.name?.[0]?.toUpperCase()||"?"}</i><span><b>{item.name||"Name not recorded"}</b><small>{item.staffId||item.email||item.id}</small></span></div><span>{item.department||"Not recorded"}</span><span>{item.role||"Not recorded"}</span><span>{item.jobTitle||"Not recorded"}</span><em className={norm(item.status).toLowerCase()}>{item.status}</em><span>{item.joinedAt?new Date(item.joinedAt).toLocaleDateString():"Not recorded"}</span>{item.pendingInvitation?<span>Awaiting acceptance</span>:<button onClick={()=>open(item)}>View Profile</button>}</article>)}</div>:<div className="staff-empty"><i>♙</i><h3>{rows.length?"No matching staff":"No staff members yet"}</h3><p>{rows.length?"Try another search or filter.":"Accepted and invited staff will appear here."}</p>{!rows.length&&<button onClick={()=>go("add-staff")}>Add your first staff member</button>}</div>)}<footer><span>Showing {visible.length?(page-1)*size+1:0} to {Math.min(page*size,staff.length)} of {staff.length}</span><div><button disabled={page===1} onClick={()=>setPage(page-1)}>←</button>{Array.from({length:pages},(_,index)=><button className={page===index+1?"active":""} onClick={()=>setPage(index+1)} key={index}>{index+1}</button>)}<button disabled={page===pages} onClick={()=>setPage(page+1)}>→</button></div></footer></section></main></HospitalChrome>;
}
