import { useState } from "react";
import HospitalChrome from "../../HospitalChrome";
import { useHospitalData } from "../../hospitalData";
import { hospitalApi } from "../../../hospitalApi";

const sections = ["Facility Profile", "Verification", "Service Management", "Access Management", "Security Center"];
const permissions = ["View Patient Record", "Edit Patient Record", "Manage Appointment", "View Analytics", "Create Referral", "Accept Referral"];
const show = (value) => value || "Not recorded";

function Empty({ title, text }) { return <div className="settings-empty"><span>◇</span><b>{title}</b><p>{text}</p></div>; }
function Toggle({ checked, onChange, label }) { return <button type="button" aria-label={label} aria-pressed={checked} className={`settings-toggle ${checked ? "on" : ""}`} onClick={() => onChange(!checked)}><i /></button>; }
function Modal({ children, onClose, wide = false }) { return <div className="settings-overlay" role="presentation"><section className={`settings-modal ${wide ? "wide" : ""}`} role="dialog" aria-modal="true"><button className="settings-close" onClick={onClose} aria-label="Close">×</button>{children}</section></div>; }
function Field({ label, children }) { return <label className="settings-field"><span>{label}</span>{children}</label>; }

export default function Settings({ go }) {
  const { data, updateFacility, updateHospitalSettings, updateStaff } = useHospitalData();
  const [active, setActive] = useState("Facility Profile");
  const [view, setView] = useState("");
  const [modal, setModal] = useState(null);
  const facility = data.facility || {};
  const settings = data.settings || {};
  const saveSettings = (change) => updateHospitalSettings(change);
  const verificationStatus = settings.verificationDocuments?.length ? "In progress" : "Unverified";
  const content = active === "Facility Profile" ? <FacilityProfile facility={facility} setModal={setModal} />
    : active === "Verification" ? <Verification documents={settings.verificationDocuments || []} saveSettings={saveSettings} />
    : active === "Service Management" ? <Services settings={settings} saveSettings={saveSettings} setModal={setModal} />
    : active === "Access Management" ? <Access settings={settings} staff={data.staff} saveSettings={saveSettings} updateStaff={updateStaff} setModal={setModal} />
    : <Security settings={settings} saveSettings={saveSettings} view={view} setView={setView} setModal={setModal} />;
  return <HospitalChrome title="Setting" active="settings" go={go}><div className="settings-page"><aside className="settings-nav">{sections.map((item) => <button key={item} className={active === item ? "active" : ""} onClick={() => { setActive(item); setView(""); }}>{item}{item === "Verification" && <small>{verificationStatus}</small>}</button>)}<button className="signout" onClick={async()=>{await hospitalApi.logout();go("login")}}>Sign Out</button></aside><div className="settings-content">{content}</div></div>{modal && <SettingsModal modal={modal} close={() => setModal(null)} facility={facility} updateFacility={updateFacility} settings={settings} saveSettings={saveSettings} updateStaff={updateStaff} />}</HospitalChrome>;
}

function FacilityProfile({ facility, setModal }) {
  const details = [["Facility Name", facility.name], ["Facility Type", facility.type], ["Facility Category", facility.category], ["License Number", facility.license], ["Email Address", facility.email], ["Contact Number", facility.phone]];
  const address = [["Country", facility.country], ["State", facility.state], ["Local Gov (LGA)", facility.lga], ["District / Area", facility.district], ["Street Address", facility.address]];
  return <><h2>Facility Profile</h2><section className="facility-banner"><span className="facility-avatar">✚</span><div><h3>{show(facility.name)}</h3><p>{show(facility.email)} · {show(facility.phone)}</p>{facility.joinedAt && <small>Joined {new Date(facility.joinedAt).toLocaleDateString()}</small>}</div></section><InfoCard title="Facility Information" values={details} onEdit={() => setModal({ type: "facility" })} /><InfoCard title="Address" values={address} onEdit={() => setModal({ type: "address" })} /></>;
}
function InfoCard({ title, values, onEdit }) { return <section className="settings-card"><header><h3>{title}</h3><button onClick={onEdit}>Edit</button></header><div className="settings-info-grid">{values.map(([label, value]) => <div key={label}><small>{label}</small><strong>{show(value)}</strong></div>)}</div></section>; }

function Verification({ documents, saveSettings }) {
  const stages = [["Stage 1", "Confirm the facility is a registered organization", ["Facility Registration Certificate", "Valid ID of Facility Owner / Admin"]], ["Stage 2", "Confirm the facility can provide healthcare services", ["Healthcare Facility License", "Medical Director’s Practicing License"]], ["Stage 3", "Trust and quality verification", ["Proof of Facility Address"]]];
  const upload = (name, file) => { if (!file) return; const next = documents.filter((item) => item.name !== name).concat({ name, fileName: file.name, status: "PENDING", uploadedAt: new Date().toISOString() }); saveSettings({ verificationDocuments: next }); };
  return <><h2>Verification</h2><section className="settings-hero">▤ <div><b>License and Credentials Verification</b><p>Verify your facility license and credentials.</p></div></section>{stages.map(([title, text, items]) => <section className="settings-card verification-stage" key={title}><header><div><h3>{title}</h3><p>{text}</p></div></header>{items.map((name) => { const doc = documents.find((item) => item.name === name); return <label className="verification-row" key={name}><span><b>{name}</b><small>{doc?.fileName || "No document uploaded"}</small></span><em className={doc ? "pending" : ""}>{doc?.status || "Upload"}</em><input type="file" accept=".pdf,.png,.jpg,.jpeg" onChange={(event) => upload(name, event.target.files?.[0])} /></label>; })}</section>)}</>;
}

function Services({ settings, saveSettings, setModal }) {
  const services = settings.services || [], availability = settings.availability || [];
  return <><h2>Service Management</h2><p className="settings-subtitle">Manage services and appointment availability.</p><section className="settings-card"><header><h3>Services Offered</h3><button onClick={() => setModal({ type: "services" })}>Edit</button></header>{services.length ? <div className="service-pills">{services.map((item) => <span key={item}>{item}</span>)}</div> : <Empty title="No services added" text="Add the services offered by your facility." />}<div className="service-description"><b>Service Description</b><p>{settings.serviceDescription || "No service description has been added."}</p></div></section><section className="settings-card"><header><div><h3>Set Appointment Availability</h3><p>Control when patients can book services.</p></div><Toggle label="Facility availability" checked={Boolean(settings.available)} onChange={(available) => saveSettings({ available })} /></header>{availability.length ? <div className="availability-grid">{availability.map((slot, index) => <article key={`${slot.days}-${index}`}><b>{slot.days.join(", ")}</b><p>{slot.hours.map((hour) => `${hour.start} – ${hour.end}`).join(" · ")}</p><small>{slot.duration} minute appointments</small></article>)}</div> : <Empty title="No availability set" text="Add bookable days and hours for patients." />}<button className="settings-primary small" onClick={() => setModal({ type: "availability" })}>＋ Add availability</button></section></>;
}

function Access({ settings, staff, saveSettings, updateStaff, setModal }) {
  const roles = settings.roles || [], suspended = staff.filter((item) => String(item.status).toUpperCase() === "SUSPENDED");
  return <><h2>Access Management</h2><section className="settings-card"><header><h3>Role Table</h3><button onClick={() => setModal({ type: "role-edit", role: {} })}>＋ Custom Role</button></header>{roles.length ? <div className="settings-table"><div className="head"><span>Role Name</span><span>Description</span><span>Members</span><span>Permission</span><span /></div>{roles.map((role) => <div key={role.id}><span>{role.name}</span><span>{role.description || "Not recorded"}</span><span>{staff.filter((person) => person.role === role.name).length}</span><span>{role.permissions?.length || 0} enabled</span><button onClick={() => setModal({ type: "role", role })}>View</button></div>)}</div> : <Empty title="No roles configured" text="Create a role to define staff access." />}</section><section className="settings-card"><h3>Permissions Matrix</h3>{roles.length ? <div className="permissions-matrix"><div className="head"><span>System Feature</span>{roles.map((role) => <span key={role.id}>{role.name}</span>)}</div>{permissions.map((permission) => <div key={permission}><span>{permission}</span>{roles.map((role) => <span key={role.id}>{role.permissions?.includes(permission) ? "✓" : "×"}</span>)}</div>)}</div> : <Empty title="No permissions to display" text="Permissions appear after a role is created." />}</section><section className="settings-card"><h3>Suspended Access</h3>{suspended.length ? <div className="settings-list">{suspended.map((person) => <button key={person.id} onClick={() => setModal({ type: "suspended", person })}><span><b>{person.name}</b><small>{person.role || "Role not recorded"}</small></span><em>Suspended</em></button>)}</div> : <Empty title="No suspended staff" text="Suspended staff accounts will appear here." />}</section></>;
}

function Security({ settings, saveSettings, view, setView, setModal }) {
  if (view === "password") return <PasswordChange back={() => setView("")} />;
  if (view === "devices") return <DeviceManagement devices={settings.devices || []} saveSettings={saveSettings} back={() => setView("")} />;
  if (view === "method") return <TwoFactorMethod setModal={setModal} back={() => setView("")} />;
  return <><h2>Security Center</h2><section className="settings-hero">♢ <div><b>Your Privacy Matters</b><p>Review security settings and control account access.</p></div></section><section className="settings-card settings-actions"><button onClick={() => setModal({ type: "password-check", next: () => setView("password") })}>Change Password <span>›</span></button><button onClick={() => settings.twoFactorEnabled ? saveSettings({ twoFactorEnabled: false }) : setModal({ type: "password-check", next: () => setView("method") })}>Two Factor Authentication <Toggle label="Two factor authentication" checked={Boolean(settings.twoFactorEnabled)} onChange={(checked) => checked ? setModal({ type: "password-check", next: () => setView("method") }) : saveSettings({ twoFactorEnabled: false })} /></button><button onClick={() => setView("devices")}>Device Management <span>›</span></button></section></>;
}
function PasswordChange({ back }) { const [values, setValues] = useState({ password: "", confirm: "" }); const [error, setError] = useState(""); const valid = values.password.length >= 8 && /[A-Z]/.test(values.password) && /[a-z]/.test(values.password) && /\d/.test(values.password) && /[^A-Za-z0-9]/.test(values.password); return <><button className="settings-back" onClick={back}>← Change Password</button><form className="settings-card" onSubmit={(e) => { e.preventDefault(); setError(!valid ? "Password must meet every requirement." : values.password !== values.confirm ? "Passwords do not match." : "Password change is ready for backend submission."); }}><div className="settings-form-grid"><Field label="Enter New Password"><input type="password" value={values.password} onChange={(e) => setValues({ ...values, password: e.target.value })} /></Field><Field label="Confirm Password"><input type="password" value={values.confirm} onChange={(e) => setValues({ ...values, confirm: e.target.value })} /></Field></div><div className="password-rules"><span>{values.password.length >= 8 ? "✓" : "○"} At least 8 characters</span><span>{/[A-Z]/.test(values.password) && /[a-z]/.test(values.password) ? "✓" : "○"} Upper and lowercase letters</span><span>{/\d/.test(values.password) ? "✓" : "○"} At least one number</span><span>{/[^A-Za-z0-9]/.test(values.password) ? "✓" : "○"} At least one symbol</span></div>{error && <p className="settings-feedback">{error}</p>}<button className="settings-primary">Confirm Change</button></form></>; }
function DeviceManagement({ devices, saveSettings, back }) { return <><button className="settings-back" onClick={back}>← Device Management</button><section className="settings-hero green"><div><b>Devices where your account has been used</b><p>Remove devices you no longer recognize.</p></div></section><section className="settings-card">{devices.length ? <div className="device-list">{devices.map((device) => <article key={device.id}><div><b>{device.name || "Unnamed device"}</b><small>{device.lastSeen ? new Date(device.lastSeen).toLocaleString() : "Last seen not recorded"} · {device.platform || "Platform not recorded"}</small></div>{device.current ? <em>Current Device</em> : <button onClick={() => saveSettings({ devices: devices.filter((item) => item.id !== device.id) })}>Log Out</button>}</article>)}</div> : <Empty title="No devices recorded" text="Signed-in devices will appear here when device data is available." />}</section></>; }
function TwoFactorMethod({ setModal, back }) { const [method, setMethod] = useState(""); return <><button className="settings-back" onClick={back}>← Choose a Verification Method</button><section className="settings-hero green"><div><b>Secure your account with 2-Step Verification</b><p>Choose where to receive verification codes.</p></div></section><section className="settings-card method-select"><p>Select how you would like to receive your verification code.</p><select value={method} onChange={(e) => setMethod(e.target.value)}><option value="">Select Method</option><option value="email">Email Verification</option><option value="sms">SMS Verification</option><option value="authenticator">Authenticator App</option></select><button className="settings-primary" disabled={!method} onClick={() => setModal({ type: "code", method })}>Proceed</button></section></>; }

function SettingsModal({ modal, close, facility, updateFacility, settings, saveSettings, updateStaff }) {
  if (modal.type === "facility" || modal.type === "address") return <EditFacility type={modal.type} facility={facility} close={close} save={updateFacility} />;
  if (modal.type === "services") return <EditServices settings={settings} close={close} save={saveSettings} />;
  if (modal.type === "availability") return <Availability close={close} settings={settings} save={saveSettings} />;
  if (modal.type === "role" || modal.type === "role-edit") return <RoleModal modal={modal} settings={settings} close={close} save={saveSettings} />;
  if (modal.type === "suspended") return <Suspended person={modal.person} close={close} updateStaff={updateStaff} />;
  if (modal.type === "password-check") return <PasswordCheck close={close} next={modal.next} />;
  return <CodeModal method={modal.method} facility={facility} close={close} save={saveSettings} />;
}

function EditFacility({ type, facility, close, save }) { const keys = type === "facility" ? [["name", "Facility Name"], ["type", "Facility Type"], ["category", "Facility Category"], ["license", "License Number"], ["phone", "Phone Number"], ["email", "Email Address"]] : [["country", "Country"], ["state", "State"], ["lga", "Local Government"], ["district", "District / Area"], ["address", "Street Address"]]; const [values, setValues] = useState(() => Object.fromEntries(keys.map(([key]) => [key, facility[key] || ""]))); return <Modal onClose={close} wide><form onSubmit={(e) => { e.preventDefault(); save(values); close(); }}><h2>Edit Facility {type === "facility" ? "Information" : "Address"}</h2><div className="settings-form-grid">{keys.map(([key, label]) => <Field label={label} key={key}><input type={key === "email" ? "email" : "text"} value={values[key]} onChange={(e) => setValues({ ...values, [key]: e.target.value })} /></Field>)}</div><footer><button className="settings-primary">Save Change</button><button type="button" onClick={close}>Cancel</button></footer></form></Modal>; }
function EditServices({ settings, close, save }) { const [services, setServices] = useState(settings.services || []), [input, setInput] = useState(""), [description, setDescription] = useState(settings.serviceDescription || ""); return <Modal onClose={close}><form onSubmit={(e) => { e.preventDefault(); save({ services, serviceDescription: description }); close(); }}><h2>Edit Services Offered</h2><div className="service-pills editable">{services.map((service) => <button type="button" onClick={() => setServices(services.filter((item) => item !== service))} key={service}>{service} ×</button>)}</div><Field label="Enter Service"><div className="inline-input"><input value={input} onChange={(e) => setInput(e.target.value)} /><button type="button" onClick={() => { const value = input.trim(); if (value && !services.includes(value)) setServices([...services, value]); setInput(""); }}>＋ Apply</button></div></Field><Field label="Service Description"><textarea value={description} onChange={(e) => setDescription(e.target.value)} /></Field><footer><button className="settings-primary">Save Change</button><button type="button" onClick={close}>Cancel</button></footer></form></Modal>; }
function Availability({ close, settings, save }) { const dayNames = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]; const [days, setDays] = useState([]), [start, setStart] = useState(""), [end, setEnd] = useState(""), [duration, setDuration] = useState(""); return <Modal onClose={close}><form onSubmit={(e) => { e.preventDefault(); if (!days.length || !start || !end || !duration) return; save({ availability: [...(settings.availability || []), { days, hours: [{ start, end }], duration: Number(duration) }], available: true }); close(); }}><h2>Set Facility Availability</h2><div className="day-picker">{dayNames.map((day) => <button type="button" className={days.includes(day) ? "active" : ""} onClick={() => setDays(days.includes(day) ? days.filter((item) => item !== day) : [...days, day])} key={day}>{day}</button>)}</div><div className="settings-form-grid"><Field label="Start Time"><input type="time" value={start} onChange={(e) => setStart(e.target.value)} /></Field><Field label="End Time"><input type="time" value={end} onChange={(e) => setEnd(e.target.value)} /></Field><Field label="Appointment Duration"><input type="number" min="5" placeholder="Minutes" value={duration} onChange={(e) => setDuration(e.target.value)} /></Field></div><button className="settings-primary">Save</button></form></Modal>; }
function RoleModal({ modal, settings, close, save }) { const editing = modal.type === "role-edit"; const role = modal.role; const [name, setName] = useState(role.name || ""), [description, setDescription] = useState(role.description || ""), [allowed, setAllowed] = useState(role.permissions || []); const persist = () => { const roles = settings.roles || []; const next = role.id ? roles.map((item) => item.id === role.id ? { ...item, name, description, permissions: allowed } : item) : [...roles, { id: crypto.randomUUID(), name, description, permissions: allowed }]; save({ roles: next }); close(); }; return <Modal onClose={close}>{editing ? <form onSubmit={(e) => { e.preventDefault(); if (name.trim()) persist(); }}><h2>{role.id ? "Edit" : "Create"} Role</h2><Field label="Role Name"><input value={name} onChange={(e) => setName(e.target.value)} required /></Field><Field label="Description"><textarea value={description} onChange={(e) => setDescription(e.target.value)} /></Field><div className="permission-list">{permissions.map((permission) => <label key={permission}>{permission}<Toggle label={permission} checked={allowed.includes(permission)} onChange={(checked) => setAllowed(checked ? [...allowed, permission] : allowed.filter((item) => item !== permission))} /></label>)}</div><button className="settings-primary">Save Change</button></form> : <><button className="modal-edit" onClick={() => { close(); setTimeout(() => {}, 0); }}>View only</button><h2>{role.name}</h2><p>{role.description || "No description"}</p><div className="permission-list">{permissions.map((permission) => <p key={permission}>{permission}<b>{role.permissions?.includes(permission) ? "✓" : "×"}</b></p>)}</div><footer><button className="danger-outline" onClick={() => { save({ roles: settings.roles.filter((item) => item.id !== role.id) }); close(); }}>Delete Role</button><button onClick={close}>Cancel</button></footer></>}</Modal>; }
function Suspended({ person, close, updateStaff }) { const [confirm, setConfirm] = useState(false); return <Modal onClose={close}><div className="modal-person"><span>{person.avatar ? <img src={person.avatar} alt="" /> : person.name?.[0]}</span><h2>{confirm ? "Confirm Unsuspension" : show(person.name)}</h2></div>{confirm ? <p className="centered">This staff member will regain access assigned to their role.</p> : <div className="settings-info-grid"><div><small>Email</small><strong>{show(person.email)}</strong></div><div><small>Role</small><strong>{show(person.role)}</strong></div><div><small>Employment Type</small><strong>{show(person.employmentType)}</strong></div><div><small>Suspended At</small><strong>{person.suspendedAt ? new Date(person.suspendedAt).toLocaleString() : "Not recorded"}</strong></div></div>}<footer><button onClick={close}>Cancel</button><button className="settings-primary" onClick={() => confirm ? (updateStaff(person.id, { status: "ACTIVE", suspendedAt: null, suspensionReason: "" }), close()) : setConfirm(true)}>{confirm ? "Confirm" : "Unsuspend Staff"}</button></footer></Modal>; }
function PasswordCheck({ close, next }) { const [password, setPassword] = useState(""); return <Modal onClose={close}><form onSubmit={(e) => { e.preventDefault(); if (!password) return; close(); next(); }}><h2>Enter Password</h2><p>Confirm your password before changing sensitive security settings.</p><Field label="Password"><input type="password" value={password} onChange={(e) => setPassword(e.target.value)} required /></Field><button className="settings-primary">Continue</button></form></Modal>; }
function CodeModal({ method, facility, close, save }) { const [digits, setDigits] = useState(Array(6).fill("")), [error, setError] = useState(""); const destination = method === "sms" ? mask(facility.phone, 4) : method === "email" ? mask(facility.email, 3) : "your authenticator app"; return <Modal onClose={close}><form className="code-modal" onSubmit={(e) => { e.preventDefault(); if (!digits.every(Boolean)) return setError("Enter the complete six digit code."); save({ twoFactorEnabled: true, twoFactorMethod: method }); close(); }}><h2>Enter Verification Code</h2><p>Enter the six digit code sent to {destination || "your selected method"}.</p><div>{digits.map((digit, index) => <input key={index} inputMode="numeric" maxLength="1" value={digit} onChange={(e) => { const next = [...digits]; next[index] = e.target.value.replace(/\D/g, "").slice(-1); setDigits(next); setError(""); }} />)}</div>{error && <p className="settings-feedback">{error}</p>}<button className="settings-primary">Submit</button></form></Modal>; }
function mask(value, visible) { if (!value) return ""; const text = String(value); return `${text.slice(0, visible)}${"*".repeat(Math.max(text.length - visible, 4))}`; }
