const apiBase=import.meta.env.VITE_API_BASE_URL?.replace(/\/$/,"");
const KEY="axonlink-hospital-session";
const read=()=>{try{return JSON.parse(sessionStorage.getItem(KEY)||"null")}catch{return null}};
const write=value=>value?sessionStorage.setItem(KEY,JSON.stringify(value)):sessionStorage.removeItem(KEY);
async function request(path,options={},authenticated=false){if(!apiBase)throw new Error("The AxonLink API URL is not configured.");const session=read();const response=await fetch(`${apiBase}${path}`,{...options,headers:{"Content-Type":"application/json",...(authenticated&&session?.accessToken?{Authorization:`Bearer ${session.accessToken}`}:{}) ,...options.headers}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.message||"Request failed. Please try again.");return body}
export const hospitalApi={
 session:read,isAuthenticated:()=>Boolean(read()?.accessToken&&read()?.membership),
 registerFacility:values=>request("/api/facilities/register",{method:"POST",body:JSON.stringify(values)}),
 verifyEmail:(email,token)=>request("/api/auth/verify-email",{method:"POST",body:JSON.stringify({email,token,deviceId:"hospital-web-registration"})}),
 uploadFacilityDocument:async(facilityId,type,file,accessToken)=>{if(!apiBase)throw new Error("The AxonLink API URL is not configured.");const body=new FormData();body.append("type",type);body.append("document",file);const response=await fetch(`${apiBase}/api/facilities/${encodeURIComponent(facilityId)}/verification-documents`,{method:"POST",headers:{Authorization:`Bearer ${accessToken}`},body});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.message||"Document upload failed.");return payload},
 inspectInvitation:token=>request("/api/facilities/invitations/inspect",{method:"POST",body:JSON.stringify({token})}),
 acceptInvitation:values=>request("/api/facilities/invitations/accept",{method:"POST",body:JSON.stringify(values)}),
 login:async(email,password)=>{const auth=await request("/api/auth/login",{method:"POST",body:JSON.stringify({email,password,deviceId:"hospital-web"})});write({...auth,membership:null});try{const context=await request("/api/facilities/session",{},true);const membership=context.facilities?.find(item=>item.role==="FACILITY_ADMIN");if(!membership)throw new Error("This account has no active facility administrator workspace.");const value={accessToken:auth.accessToken,refreshToken:auth.refreshToken,user:auth.user,membership};write(value);return value}catch(error){write(null);throw error}},
 inviteStaff:(email,role)=>{const session=read();if(!session?.membership?.facility?.id)throw new Error("Select an active facility workspace first.");return request(`/api/facilities/${session.membership.facility.id}/invitations`,{method:"POST",body:JSON.stringify({email,role})},true)},
 listStaff:()=>{const session=read();if(!session?.membership?.facility?.id)throw new Error("Select an active facility workspace first.");return request(`/api/facilities/${session.membership.facility.id}/staff`,{},true)},
 getStaff:membershipId=>{const session=read();if(!session?.membership?.facility?.id)throw new Error("Select an active facility workspace first.");return request(`/api/facilities/${session.membership.facility.id}/staff/${encodeURIComponent(membershipId)}`,{},true)},
 setStaffStatus:(membershipId,status)=>{const session=read();if(!session?.membership?.facility?.id)throw new Error("Select an active facility workspace first.");return request(`/api/facilities/${session.membership.facility.id}/staff/${encodeURIComponent(membershipId)}`,{method:"PATCH",body:JSON.stringify({status})},true)},
 removeStaff:membershipId=>{const session=read();if(!session?.membership?.facility?.id)throw new Error("Select an active facility workspace first.");return request(`/api/facilities/${session.membership.facility.id}/staff/${encodeURIComponent(membershipId)}`,{method:"DELETE"},true)},
 listPatients:()=>{const session=read();if(!session?.membership?.facility?.id)throw new Error("Select an active facility workspace first.");return request(`/api/facilities/${session.membership.facility.id}/patients`,{},true)},
 registerPatient:values=>{const session=read();if(!session?.membership?.facility?.id)throw new Error("Select an active facility workspace first.");return request(`/api/facilities/${session.membership.facility.id}/patients`,{method:"POST",body:JSON.stringify(values)},true)},
 getPatient:facilityPatientId=>{const session=read();if(!session?.membership?.facility?.id)throw new Error("Select an active facility workspace first.");return request(`/api/facilities/${session.membership.facility.id}/patients/${encodeURIComponent(facilityPatientId)}`,{},true)},
 clinicalRecords:facilityPatientId=>{const session=read();if(!session?.membership?.facility?.id)throw new Error("Select an active facility workspace first.");return request(`/api/facilities/${session.membership.facility.id}/patients/${encodeURIComponent(facilityPatientId)}/clinical-records`,{},true)},
 createClinicalRecord:(facilityPatientId,category,values)=>{const session=read();if(!session?.membership?.facility?.id)throw new Error("Select an active facility workspace first.");return request(`/api/facilities/${session.membership.facility.id}/patients/${encodeURIComponent(facilityPatientId)}/clinical-records/${encodeURIComponent(category)}`,{method:"POST",body:JSON.stringify(values)},true)},
 updateClinicalRecord:(facilityPatientId,category,recordId,values)=>{const session=read();if(!session?.membership?.facility?.id)throw new Error("Select an active facility workspace first.");return request(`/api/facilities/${session.membership.facility.id}/patients/${encodeURIComponent(facilityPatientId)}/clinical-records/${encodeURIComponent(category)}/${encodeURIComponent(recordId)}`,{method:"PATCH",body:JSON.stringify(values)},true)},
 listAppointments:()=>{const session=read();if(!session?.membership?.facility?.id)throw new Error("Select an active facility workspace first.");return request(`/api/facilities/${session.membership.facility.id}/appointments`,{},true)},
 appointmentOptions:()=>{const session=read();if(!session?.membership?.facility?.id)throw new Error("Select an active facility workspace first.");return request(`/api/facilities/${session.membership.facility.id}/appointment-options`,{},true)},
 createAppointment:values=>{const session=read();if(!session?.membership?.facility?.id)throw new Error("Select an active facility workspace first.");return request(`/api/facilities/${session.membership.facility.id}/appointments`,{method:"POST",body:JSON.stringify(values)},true)},
 updateAppointment:(appointmentId,values)=>{const session=read();if(!session?.membership?.facility?.id)throw new Error("Select an active facility workspace first.");return request(`/api/facilities/${session.membership.facility.id}/appointments/${encodeURIComponent(appointmentId)}`,{method:"PATCH",body:JSON.stringify(values)},true)},
 listReferrals:()=>{const session=read();if(!session?.membership?.facility?.id)throw new Error("Select an active facility workspace first.");return request(`/api/facilities/${session.membership.facility.id}/referrals`,{},true)},
 getReferral:referralId=>{const session=read();if(!session?.membership?.facility?.id)throw new Error("Select an active facility workspace first.");return request(`/api/facilities/${session.membership.facility.id}/referrals/${encodeURIComponent(referralId)}`,{},true)},
 updateReferral:(referralId,change)=>{const session=read();if(!session?.membership?.facility?.id)throw new Error("Select an active facility workspace first.");return request(`/api/facilities/${session.membership.facility.id}/referrals/${encodeURIComponent(referralId)}`,{method:"PATCH",body:JSON.stringify(typeof change==="string"?{action:change}:change)},true)},
 logout:async()=>{const current=read();try{await request("/api/auth/logout",{method:"POST",body:JSON.stringify({refreshToken:current?.refreshToken||""})})}finally{write(null)}}
};
