import { useMemo, useState } from "react";
import HospitalChrome from "../HospitalChrome";
import { useHospitalData } from "../hospitalData";
import { useFacilityPatients } from "../patient/useFacilityPatients";

const norm=v=>String(v||"").trim().toUpperCase().replace(/[ -]+/g,"_");
const kind=r=>norm(r.direction||r.referralType||r.type||"INTERNAL");
const stat=r=>norm(r.status||"PENDING");
const done=r=>["COMPLETED","ACCEPTED"].includes(stat(r));
const percent=(n,total)=>total?Math.round(n/total*100):0;
const groups=(items,get)=>Object.entries(items.reduce((map,item)=>{const key=get(item);if(key)map[key]=(map[key]||0)+1;return map},{})).sort((a,b)=>b[1]-a[1]);
const first=(...values)=>values.find(v=>v!==undefined&&v!==null&&v!=="");
const average=values=>{const clean=values.map(Number).filter(Number.isFinite);return clean.length?Math.round(clean.reduce((a,b)=>a+b,0)/clean.length):"Not recorded"};

function Empty({title="No analytics available",text="Analytics will appear when activity is recorded."}){return <div className="analysis-empty"><span>⌁</span><b>{title}</b><p>{text}</p></div>}
function Period({value,onChange}){return <select className="analysis-period" value={value} onChange={e=>onChange(e.target.value)}><option value="30">Last 30 days</option><option value="90">Last 3 months</option><option value="180">Last 6 months</option><option value="365">Last year</option></select>}
function Section({title,tone="",children}){return <section className={`analysis-section ${tone}`}><header><h2>{title}</h2></header>{children}</section>}
function Metrics({items}){return <div className="analysis-metrics">{items.map(([label,value,suffix=""])=> <article key={label}><span>{label}</span><b>{value}{suffix}</b></article>)}</div>}
function Bars({data,total}){return data.length?<div className="analysis-bars">{data.map(([label,count])=><div key={label}><span>{label}</span><i><b style={{width:`${percent(count,total)}%`}}/></i><strong>{count} <small>{percent(count,total)}%</small></strong></div>)}</div>:<Empty/>}
function Table({columns,rows,title="No records available"}){return rows.length?<div className="analysis-table"><div className="head">{columns.map(c=><span key={c}>{c}</span>)}</div>{rows.map((row,i)=><div key={row.id||i}>{row.cells.map((cell,j)=><span key={j}>{cell}</span>)}</div>)}</div>:<Empty title={title}/>}

export default function AnalysisDashboard({go}){
 const {data}=useHospitalData();const [period,setPeriod]=useState("180"),[tab,setTab]=useState("INTERNAL");
 const {patients,loading:patientsLoading,error:patientsError}=useFacilityPatients();
 const cutoff=useMemo(()=>{const d=new Date();d.setDate(d.getDate()-Number(period));return d},[period]);
 const recent=(items,get)=>items.filter(item=>{const raw=get(item);return !raw||new Date(raw)>=cutoff});
 const appointments=recent(data.appointments,i=>i.start||i.createdAt),referrals=recent(data.referrals,i=>i.createdAt||i.referralDate||i.date),staff=data.staff;
 const complete=appointments.filter(i=>stat(i)==="COMPLETED").length;
 const waits=appointments.map(i=>Number(i.waitingMinutes||i.waitTimeMinutes)).filter(Number.isFinite);
 const genders=groups(patients,i=>i.gender||"Not recorded"),ages=groups(patients,i=>{const age=Number(i.age);return !Number.isFinite(age)?"Not recorded":age<18?"0–17":age<30?"18–29":age<60?"30–59":"60+"});
 const noData=!appointments.length&&!referrals.length&&!patients.length&&!staff.length;
 return <HospitalChrome title="Report and Analysis" active="analysis" go={go}><main className="analysis-page"><section className="analysis-hero"><span>♜</span><div><h1>Reports & Analytics Hub</h1><p>Facility performance calculated from your records.</p></div><Period value={period} onChange={setPeriod}/></section>{noData&&<Empty title="No report data yet" text="Patients, appointments, referrals and staff activity will populate this dashboard."/>}
 <Section title="Patient Analysis" tone="purple"><Metrics items={[["Total Patients",patientsLoading||patientsError?"—":patients.length],["Appointments Completed",complete],["Pending Appointments",appointments.filter(i=>["PENDING","UPCOMING"].includes(stat(i))).length],["Referrals Sent",referrals.filter(i=>kind(i)==="OUTGOING").length],["Referrals Received",referrals.filter(i=>kind(i)==="INCOMING").length],["Average Patient Wait",waits.length?average(waits):"Not recorded",waits.length?" min":""]]}/>{patientsError&&<p className="analysis-data-error">Patient analytics are temporarily unavailable.</p>}<div className="analysis-grid"><article><h3>Patient Gender</h3><Bars data={genders} total={patients.length}/></article><article><h3>Age Groups</h3><Bars data={ages} total={patients.length}/></article></div></Section>
 <Section title="Appointment Analytics" tone="green"><Metrics items={[["Total Scheduled",appointments.length],["Upcoming",appointments.filter(i=>stat(i)==="UPCOMING").length],["Completed",complete],["Canceled",appointments.filter(i=>stat(i)==="CANCELED").length],["No-show",appointments.filter(i=>["NO_SHOW","MISSED"].includes(stat(i))).length],["Pending Requests",appointments.filter(i=>stat(i)==="PENDING").length]]}/><div className="analysis-grid"><article><h3>Status Distribution</h3><Bars data={groups(appointments,stat)} total={appointments.length}/></article><article><h3>Appointment Sources</h3><Bars data={groups(appointments,i=>i.source||"Not recorded")} total={appointments.length}/></article></div><h3>Department Workload</h3><CountTable data={groups(appointments,i=>i.department||i.specialty||"Not recorded")} total={appointments.length} label="Department"/></Section>
 <Section title="Referral Analytics" tone="purple"><Metrics items={[["Total Referrals",referrals.length],["Internal Referrals",referrals.filter(i=>kind(i)==="INTERNAL").length],["Incoming Referrals",referrals.filter(i=>kind(i)==="INCOMING").length],["Outgoing Referrals",referrals.filter(i=>kind(i)==="OUTGOING").length],["Completion Rate",percent(referrals.filter(done).length,referrals.length),"%"]]}/><ReferralReport referrals={referrals} tab={tab} setTab={setTab}/></Section>
 <Section title="Staff Performance Analytics" tone="green"><Metrics items={[["Total Staff",staff.length],["Active Staff",staff.filter(i=>stat(i)==="ACTIVE").length],["Suspended Staff",staff.filter(i=>stat(i)==="SUSPENDED").length],["Average Consultation Time",average(staff.map(i=>i.averageConsultationMinutes)),average(staff.map(i=>i.averageConsultationMinutes))==="Not recorded"?"":" min"]]}/><Table columns={["Staff","Role","Appointments","Completed","Canceled","No-show"]} title="No staff performance data" rows={staff.map(person=>{const assigned=appointments.filter(i=>i.clinicianId===person.id||i.clinician===person.name);return{id:person.id,cells:[person.name||"Name not recorded",person.role||person.category||"Role not recorded",assigned.length,assigned.filter(i=>stat(i)==="COMPLETED").length,assigned.filter(i=>stat(i)==="CANCELED").length,assigned.filter(i=>["NO_SHOW","MISSED"].includes(stat(i))).length]}})}/></Section>
 </main></HospitalChrome>
}
function CountTable({data,total,label}){return <Table columns={[label,"Count","Percentage"]} rows={data.map(([name,count])=>({cells:[name,count,`${percent(count,total)}%`]}))}/>}
function ReferralReport({referrals,tab,setTab}){const selected=referrals.filter(i=>kind(i)===tab),internal=tab==="INTERNAL";const facilities=groups(selected,i=>first(i.facilityName,i.facility?.name,i.referringFacility?.name,i.toFacility?.name));const departments=internal?groups(selected,i=>`${first(i.fromDepartment,i.from?.department)||"Not recorded"} → ${first(i.toDepartment,i.to?.department)||"Not recorded"}`):groups(selected,i=>first(i.department,i.specialty,i.toDepartment,i.fromDepartment));return <div className="referral-analysis"><nav>{["INTERNAL","INCOMING","OUTGOING"].map(item=><button key={item} className={tab===item?"active":""} onClick={()=>setTab(item)}>{item[0]+item.slice(1).toLowerCase()} Referrals</button>)}</nav>{selected.length?<><Metrics items={[["Total",selected.length],["Completed",selected.filter(done).length],["Pending",selected.filter(i=>["PENDING","REQUESTED","PENDING_REQUEST"].includes(stat(i))).length],["Completion Rate",percent(selected.filter(done).length,selected.length),"%"]]}/><div className="analysis-grid"><article><h3>Referral Status</h3><Bars data={groups(selected,stat)} total={selected.length}/></article><article><h3>{internal?"Department Referral Flow":tab==="INCOMING"?"Top Referring Facilities":"Top Referral Destinations"}</h3>{internal?<CountTable data={departments} total={selected.length} label="Flow"/>:<CountTable data={facilities.slice(0,5)} total={selected.length} label="Facility"/>}</article></div>{!internal&&<><h3>Referral Departments</h3><CountTable data={departments} total={selected.length} label="Department"/></>}</>:<Empty title={`No ${tab.toLowerCase()} referral data`} text={`Analytics will appear after ${tab.toLowerCase()} referrals are recorded.`}/>}</div>}
